=== Radnere/1site/Niskov/blog.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="blog">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="post" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element type="xsd:string" name="title">
                            <xsd:element type="xsd:string" name="text">
                            <xsd:element type="xsd:date" name="date">
                            <xsd:element type="xsd:string" name="theme">
                            <xsd:element type="xsd:string" name="keywords">
                            <xsd:element type="xsd:string" name="files">
                            <xsd:element name="records">
                            <xsd:complexType>
                            <xsd:sequence>
                            <xsd:element name="comment" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                            <xsd:sequence>
                              <xsd:element name="author">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:pattern value="[а-яА-Яa-zA-Z0-9\-_]{3,20}"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                            <xsd:element type="xsd:string" name="text">
                            <xsd:element name="responses">
                            <xsd:complexType>
                            <xsd:sequence>
                            <xsd:element name="response" maxOccurs="unbounded" minOccurs="0">
                            <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="author">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:pattern value="[а-яА-Яa-zA-Z0-9\-_]{3,20}"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                            <xsd:element type="xsd:string" name="text">
                            </xsd:sequence>
                            </xsd:complexType>
                            </xsd:element>
                            </xsd:sequence>
                            </xsd:complexType>
                            </xsd:element>
                            </xsd:sequence>
                            </xsd:complexType>
                            </xsd:element>
                            </xsd:sequence>
                            </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Radnere/1site/Niskov/blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="blog.xsl"?>
<blog  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="blog.xsd">
    <post>
        <title>Зимняя рыбалка</title>
        <text>
Эта тема для всех тех, кто не желает выдавать свои сокровенно-секретные рыбные места или не хочет отчитываться отдельно по какому-нибудь конкретному водоёму...
Также она заинтересует тех, кому лень писать подробные отчёты с фотографиями. Здесь можно обойтись буквально несколькими фразами, типа: "там-то клюёт.." или "сегодня не клевало".
Можно даже немного пофлудить (разумеется на рыбацкую тему) !</text>
        <date>2017-12-09</date>
        <theme>Только с рыбалки...</theme>
        <keywords>Fish, Fishing, cold</keywords>
        <files></files>
        <records>
            <comment>
                <author>Рыбачелло</author>
                <text>Всем привет и с праздниками! Только с Метайловки. Упор в жерлицы. Стоял вдоль острова, и по руслу и в камышах. Итог- ни одного флага!!!! под камышем мелкий окунь, на русле за два часа три плотвы. Половина рыбаков к 13 часам потянулись к берегу. Такого пролета я не помню...</text>
                
                <responses>
                    <response>
                        <author>Fisherman</author>
                        <text>Видимо пару дней назад всю щуку с метайловки выгребли))</text>
                    </response>
                    <response>
                        <author>YurZa</author>
                        <text>Ага. И шнурков и плотву. Начисто.</text>
                    </response>
                    <response>
                        <author>Аstel</author>
                        <text>Сегодня были в Рубежном за мостом , тоже тишина , после обеда приезжали два рыбака с Метайловки говорили, что на Метайловке сегодня болт, по жерлицам в Рубежном сегодня затишье , 1 шнурок уплывший подростать и 2 сработки со сбитыми живцами , на удочки пиписечная плотва размер пачка сигарет пошла за шнурком))) и окуней с полтора десятка разнокалиберных но лунок насверлили достаточно по руслу от моста ходили блеснильщики но безрезультатно .</text>
                    </response>
                </responses>
            </comment>
            <comment>
                <author>MohamedAboOkail</author>
                <text>по руслу в районе моста лед прочный?</text>
            </comment>
        </records>
    </post>
    <post>
        <title>Рыбалка ONLINE</title>
        <date>2018-01-04</date>
        <theme>Тут есть местоположения всех крутейших уловных мест</theme>
        <keywords>Fishplace, bestfishing</keywords>
        <files></files>
        <records>
            <comment>
                <author>Professor</author>
                <text> мы сейчас по местному на рыбалочке, и уже два "выстрела" видел, и даже есть результат </text>
                <responses>
                    <response>
                        <author>Swag</author>
                        <text>Мартовая, на вчерашних лунках глухо, товарищ распочинился и все</text>
                    </response>
                </responses>
            </comment>
            <comment>
                <author>Sh_Roman</author>
                <text>Только со Старого Салтова под Чёрныйм лесом, клев просто отвратительный, еле вымучал на 6.5м десяток плотвин, в 11 собрались уехали, на поплавок немного лучше, 2 десятка у товарища, но они до сих пор там</text>
                <responses>
                    <response>
                        <author>-Pacifist-</author>
                        <text>Пушки холостые...Клев стабильный..На норму идем..</text>
                    </response>
                    <response>
                        <author>Sazan</author>
                        <text>Хотомля, ( насоска).глубина 6,5 клев есть, но одна мелоч.</text>
                    </response>
                    <response>
                        <author>VOVAN</author>
                        <text>Травянка полный ноль.</text>
                    </response>
                </responses>
            </comment>
        </records>
    </post>
    <post>
        <title>Урок 1. Создание меню</title>
        <text>Всем привет. Узнав о Unity3D, я очень обрадовался. Это была вторая вещь в геймдевлопе, которая меня зацепила простотой и интуитивностью (первая Game Maker). Так как я не люблю видеоуроки (сам не знаю почему), в поисках уроков очень сильно напрягался, из-за малого количества текстовых уроков. Поэтому решил написать данный цикл статей, для таких же любителей текстовых уроков как я. Так как этот цикл ориентирован на новичков, попутно будут изучаться возможности Unity3D.</text>
        <date>2013-11-06</date>
        <theme>Unity3D. Создание RPG.</theme>
        <keywords>unity, rpg, создание игр</keywords>
        <files></files>
        <records>
            <comment>
                <author>JHawk</author>
                <text>Да будет тебе известно, что больше 90% всех уроков которые пишутся по юнити пишутся для людей уже знакомых с интерфесом редактори и умеющим с ним маломальски работать! И ненадо писать "Созадние РПГ", потому что ты все равно не напишишь ничего толкового! АБСОЛЮТНО НИЧЕГО!</text>
                <responses>
                    <response>
                        <author>rak</author>
                        <text>Во вторых, напишу я что толковое или нет не тебе судить так как у само за душой ни чего нет, кроме змейки. Да и высказывания надо делать после того как сам что ни будь полезное сделаешь для сообщества. И спецом для тебя могу в перед уроков доделать то что в итоге получится, или дождешься вместе со всеми окончания цикла статей?</text>
                    </response>
                    <response>
                        <author>kostya3231</author>
                        <text>ты что, ясновидящий? Если тебе не нужны эти уроки, не смотри эту тему, всего делов. Если кому то пригодится - будет хорошо. Парень же расписал план, сообщил о том что будет дальше. Материал, который он (переработанный) выкладывает, есть в виде видеуроков у двух людей - в сжатом ввиде у Огосоды (который тот так и не закончил), и на английском языке у чувака с ютуба. Оба варианта - видеоуроки, а наш парень делает эту тему для людей предпочитающих текстовый формат, которых, кстати, много (мой брат например). Что тоже достойно уважения.</text>
                    </response>
                </responses>
            </comment>
        </records>
    </post>
    <post>
        <title>Территория Сталкера</title>
        <text>Выкладываем здесь сталкерские шутки, анекдоты и приколы.</text>
        <date>2021-12-13</date>
        <theme>Сталкерский Юмор</theme>
        <keywords>Stalker, anomaly</keywords>
        <files></files>
        <records>
            <comment>
                <author>Тоха</author>
                <text>анекдот;
какая самая лучшая машина зоны?-говорит сталкер.
запорожиц!-ответил сталкер.
это почему?
да потомучто никто не украдет и багажник спереди,легко за хабаром следить!

конец...</text>
                <responses>
                    <response>
                        <author>Gavaez</author>
                        <text>ещё один анекдот:
Приходит как-то сталкер к доктору на обслндование тот его осматривает и всё время говорит; "хорошо хорошо".сталкер у него спрашивает: "что хорошо?" а док ему отвечает:"хорошо что не у меня"</text>
                    </response>
                </responses>
            </comment>
            <comment>
                <author>Карась</author>
                <text>Анекдот:
Тренирует контролёр слепого пса трюкам разным, типа сидеть, лежать, умри, а рядом стоит зомби и прикалывается, мол:
-Ничё у тебя не выйдет, зря стараешься!

А контролёр ему отвечает:

-Слышь Сталкер, молчи, ты мне тапочки приносить тоже не сразу начал!</text>
                <responses>
                    <response>
                        <author>ПаблоПикасо</author>
                        <text>Нашел как то сталер Иванов исполнитель желаний....и неделю не просыхал.</text>
                    </response>
                </responses>
            </comment>
        </records>
    </post>
    <post>
        <title>Bon Jovi - Roller Coaster</title>
        <text>Bon  jovi I hope you know the impact you have made around the world and all of the lives you've touched your music has helped me through some tough times and continues to inspires me daily thank you.</text>
        <date>2017-05-15</date>
        <theme>Bon Jovi</theme>
        <keywords>Bon Jovi, music</keywords>
        <files></files>
        <records>
            <comment>
                <author>Krynn Fuller</author>
                <text>ZuesTheElderGod  SAME HERE BROTHA</text>
                <responses>
                    <response>
                        <author>Patriche Patriche</author>
                        <text>Can't say it better.... same here! 3</text>
                    </response>
                    <response>
                        <author>ZeusTheElderGod</author>
                        <text>Thanasis Karas Phoenix,AZ why?</text>
                    </response>
                    <response>
                        <author>kostya3231</author>
                        <text>Exactly!!!</text>
                    </response>
                </responses>
            </comment>
        </records>
    </post>
    <post>
        <title>Психушка</title>
        <text>Все психи сюда</text>
        <date>2020-07-16</date>
        <theme>Все психи тут собрались</theme>
        <keywords>Псих, Психушка</keywords>
        <files></files>
        <records>
            <comment>
                <author>Костя</author>
                <text>АОаоаооааа</text>
